Revert D137868 "[libc] Fix builtin definition for memory functions"
This reverts commit da5d00ad0cf4d45e38287280c670b08e84e27411.

This caused -Wmacro-redefined
```
.../libc/src/string/memory_utils/op_x86.h:31:9: error: '_mm512_cmpneq_epi8_mask' macro redefined [-Werror,-Wmacro-redefined]
        ^
.../lib/clang/google3-trunk/include/avx512bwintrin.h:294:9: note: previous definition is here
        ^
```

NOKEYCHECK=True
GitOrigin-RevId: 310b619e9505c373713e46ed466abd83ffcda3fa