[libc] Remove broken __builtin_aarch64_wsr fallback in set_thread_ptr (#197295)
The fallback used __builtin_aarch64_wsr (32-bit) instead of
__builtin_aarch64_wsr64, truncating the 64-bit thread pointer value and
causing non-deterministic runtime crashes.

Modern GCC correctly warns about it and -Werror=conversion catches it.

```
/var/tmp/portage/llvm-runtimes/libc-22.1.5/work/libc/startup/linux/aarch64/tls.cpp: In function ‘bool __llvm_libc_22_1_5_::set_thread_ptr(uintptr_t)’:
/var/tmp/portage/llvm-runtimes/libc-22.1.5/work/libc/startup/linux/aarch64/tls.cpp:90:38: error: conversion from ‘uintptr_t’ {aka ‘long unsigned int’} to ‘unsigned int’ may change value [-Werror=conversion]
   90 |   __builtin_aarch64_wsr("tpidr_el0", val);
      |                                      ^~~
cc1plus: all warnings being treated as errors
```
NOKEYCHECK=True
GitOrigin-RevId: b16e3a0db7759ec31de981692e10c19d930c9dac